# Generated by Django 5.1.5 on 2025-11-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piscine',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
