# Generated by Django 5.1.5 on 2025-11-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_piscine_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piscine',
            name='reduction',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
