# Generated by Django 5.1.5 on 2026-01-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_piscine_reduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code_client',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
