# Generated by Django 5.1.5 on 2025-08-20 23:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestation',
            name='fait_par',
        ),
        migrations.AddField(
            model_name='prestation',
            name='fait_par',
            field=models.ManyToManyField(null=True, related_name='prestations_realisees', to=settings.AUTH_USER_MODEL),
        ),
    ]
