# Generated by Django 5.1.5 on 2025-08-30 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_remove_prestation_fait_par_prestation_fait_par'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='quantite',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='fait_par',
            field=models.ManyToManyField(related_name='prestations_realisees', to=settings.AUTH_USER_MODEL),
        ),
    ]
