# Generated by Django 5.1.5 on 2025-09-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_prestation_quantite_alter_prestation_fait_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='initprestation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmé', 'Confirmé')], default='en_attente', max_length=10),
        ),
    ]
