# Generated by Django 5.1.5 on 2025-12-02 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_repartitionmontantprestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartitionmontantprestation',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.service'),
        ),
    ]
