# Generated by Django 5.1.5 on 2026-01-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_repartitionmontantprestation_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='initprestation',
            name='montant_attribue',
            field=models.BooleanField(default=False),
        ),
    ]
