# Generated by Django 5.1.5 on 2026-01-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_initprestation_montant_attribue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvisionnement',
            name='pau',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
