# Generated by Django 5.1.5 on 2026-01-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_alter_approvisionnement_pau_alter_produit_prix_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='designation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
