# Generated by Django 5.1.5 on 2026-01-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_alter_produit_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvisionnement',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
