# Generated by Django 5.1.5 on 2026-03-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_alter_approvisionnement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initprestation',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
