# Generated by Django 5.1.5 on 2026-03-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_alter_initprestation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
