# Generated by Django 5.1.5 on 2026-07-04 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'check_out_time'], name='pointage_at_employe_3a6e02_idx'), models.Index(fields=['employee', 'check_in_time'], name='pointage_at_employe_3122a1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('check_out_time__isnull', True)), fields=('employee',), name='unique_open_attendance_per_employee')],
            },
        ),
    ]
