# Generated by Django 5.1.5 on 2026-07-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-check_in_time']},
        ),
    ]
