# Generated by Django 5.1.5 on 2025-08-27 21:44
import uuid
from django.db import migrations, models


def gen_username(apps, schema_editor):
    Employe = apps.get_model("employe", "Employe")
    for emp in Employe.objects.all():
        base = (emp.first_name or "user").lower().replace(" ", "")
        # Ajouter 8 caracteres uniques d'un uuid
        unique_part = str(uuid.uuid4())[:8]
        emp.username = f"{base}_{unique_part}"
        emp.save(update_fields=["username"])


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name="employe",
            name="username",
            field=models.CharField(max_length=150, unique=True, null=True, blank=True),
        ),
        migrations.RunPython(gen_username),
        migrations.AlterField(
            model_name="employe",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
