# Generated by Django 5.1.5 on 2025-08-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_add_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
