# Generated by Django 5.1.5 on 2025-07-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnementboisson',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
