# Generated by Django 5.1.5 on 2025-08-02 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_initcontroleplats_platscontrolles'),
    ]

    operations = [
        migrations.AddField(
            model_name='platscontrolles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platscontrolles',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
