# Generated by Django 5.1.5 on 2025-08-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_platscontrolles_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvisionnementboisson',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
