# Generated by Django 5.1.5 on 2026-01-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_approvisionnementboisson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvisionnementboisson',
            name='prix_achat_unit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boisson',
            name='prix_achat',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
